/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class projectnine_cn_com_androidndkdemo1_Java2C */

#ifndef _Included_projectnine_cn_com_androidndkdemo1_Java2C
#define _Included_projectnine_cn_com_androidndkdemo1_Java2C
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     projectnine_cn_com_androidndkdemo1_Java2C
 * Method:    getFromC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_projectnine_cn_com_androidndkdemo1_Java2C_getFromC
  (JNIEnv *, jobject);

/*
 * Class:     projectnine_cn_com_androidndkdemo1_Java2C
 * Method:    login
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_projectnine_cn_com_androidndkdemo1_Java2C_login
  (JNIEnv *, jobject, jstring, jstring, jint);

/*
 * Class:     projectnine_cn_com_androidndkdemo1_Java2C
 * Method:    modifyValue
 * Signature: ([I)[I
 */
JNIEXPORT jintArray JNICALL Java_projectnine_cn_com_androidndkdemo1_Java2C_modifyValue
  (JNIEnv *, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif
