/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class projectnine_cn_com_androidzengliangupdate_PatchUtils */

#ifndef _Included_projectnine_cn_com_androidzengliangupdate_PatchUtils
#define _Included_projectnine_cn_com_androidzengliangupdate_PatchUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     projectnine_cn_com_androidzengliangupdate_PatchUtils
 * Method:    combine
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_projectnine_cn_com_androidzengliangupdate_PatchUtils_combine
  (JNIEnv *, jclass , jstring , jstring , jstring );

#ifdef __cplusplus
}
#endif
#endif
