/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class projectnine_cn_com_androidzengliangupdate_Bspatch */

#ifndef _Included_projectnine_cn_com_androidzengliangupdate_Bspatch
#define _Included_projectnine_cn_com_androidzengliangupdate_Bspatch
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     projectnine_cn_com_androidzengliangupdate_Bspatch
 * Method:    bsPatch
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_projectnine_cn_com_androidzengliangupdate_Bspatch_bsPatch
  (JNIEnv *, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
